name: Upcoming Competition Automation

on:
  pull_request:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '30 18 *  * TUE'

jobs:
  get-comps-write-to-ui:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install -r requirements.txt

      - name: execute python scripts
        run: |
          cd python
          python get_comps.py 
      # python write_comps_to_ui.py

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: prettify code
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_options: --write **/*.{js,html,css,md}
